import "./globals.css";
import { archivo } from "./fonts/fonts";
import { ThemeProvider } from "@/components/theme-provider";
import Script from "next/script";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${archivo.className} antialiased`}>
        <Script src="/simplepeer.min.js"  />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
        {/* Use Next.js Script component to load simplepeer.min.js */}
      </body>
    </html>
  );
}
